name: Build & Push Docker Images into Docker Hub

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "sumegh20" --password-stdin
        docker image build -t sumegh20/hello-world-app:latest .
        docker push sumegh20/hello-world-app:latest